name = "optiline-systems-static"
compatibility_date = "2026-07-16"

[build]
command = "pnpm install && pnpm build"
cwd = "./"

[assets]
directory = "./dist"

[env.production]
name = "optiline-systems-static-prod"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

